name: Visual Barista
favicon: null
layout_spectrum: 0.010552838444709778
typography_spectrum: 0.1726893379818648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4903062202502042
  lightness: 0.07375957677140832
  saturation: 0.7703601848334074
  rhythmicContrast: 0.5249808453954756
purpose: []
